import Link from "next/link";
import { createClient } from "@/lib/supabase/server";
import { requireUser } from "@/lib/auth";
import { loadMonthlyRecap } from "@/lib/monthly-recap-data";
import { currentRecapMonth, recapLabel, validRecapMonth } from "@/lib/recap-month";
import { CoverImage } from "@/components/CoverImage";
import { ScoreBadge } from "@/components/ScoreBadge";
import { RecapShareCard } from "@/components/RecapShareCard";
import { formatScore } from "@/lib/utils";

export default async function MonthlyRecapPage({searchParams}:{searchParams:Promise<{month?:string}>}){
  const month=validRecapMonth((await searchParams).month);
  const user=await requireUser(),client=await createClient();
  let data:Awaited<ReturnType<typeof loadMonthlyRecap>>|null=null;
  try{data=await loadMonthlyRecap(client,user.id,month);}catch{console.error(JSON.stringify({event:"monthly_recap_load_failed"}));}
  const recap=data?.recap;
  const songs=recap?.picks.length?recap.picks:recap?.tracks??[];
  return <div className="space-y-7"><header className="flex flex-wrap items-end justify-between gap-4"><div><Link href="/profile" className="text-sm text-accent">← Profile</Link><p className="eyebrow mt-4">On record</p><h1 className="font-serif text-3xl font-bold tracking-tight text-ink">Your month in music</h1><p className="mt-1 text-sm text-muted">Your scores, your favourites, your differences of opinion.</p></div><form className="flex items-end gap-2"><label className="text-xs text-muted">Recap month<input type="month" name="month" aria-label="Recap month" min="2000-01" max={currentRecapMonth()} defaultValue={month} className="input mt-1"/></label><button type="submit" className="btn btn-outline">View</button></form></header><p className="text-sm font-semibold text-accent">{recapLabel(month)}{month===currentRecapMonth()?" · So far":""}</p>
    {!recap?<section role="status" className="surface-panel p-6"><p>Your recap couldn’t load. Reload to try again.</p><a href={`/recap?month=${month}`} className="btn btn-outline mt-3">Retry</a></section>:<div className="grid items-start gap-8 lg:grid-cols-[1fr_320px]"><div className="space-y-7">
      <section className="surface-panel p-5 sm:p-6"><h2 className="font-serif text-2xl font-semibold text-ink">{recap.albums.length?`${recap.albums.length} ${recap.albums.length===1?"album":"albums"}, on record.`:"A quieter month."}</h2><p className="mt-2 text-sm text-muted">Rated or revisited{recap.average!==null?` · ${formatScore(recap.average)}/10 average`:" · No scored albums updated this month"}.</p></section>
      <section><h2 className="mb-3 font-serif text-xl font-semibold text-ink">Highest scores this month</h2>{recap.albums.length?<div className="grid grid-cols-3 gap-3">{recap.albums.slice(0,3).map(row=><Link key={row.album_id} href={`/album/${row.album_id}`}><CoverImage url={row.album!.cover_image_url} alt={`${row.album!.title} cover`} className="aspect-square w-full rounded-xl"/><h3 className="mt-2 text-sm font-semibold text-ink">{row.album!.title}</h3><p className="text-xs text-muted">{row.album!.artist}</p><ScoreBadge score={Number(row.overall_rating)} className="mt-1 text-base"/></Link>)}</div>:<p className="text-sm text-muted">Rate an album’s tracks to begin, or choose another month.</p>}</section>
      <section><div className="mb-3 flex flex-wrap items-center justify-between gap-2"><h2 className="font-serif text-xl font-semibold text-ink">{recap.picks.length?"Your monthly favourite songs":"Favourite tracks from these albums"}</h2><Link href={`/favourites/${month}`} className="text-xs text-accent">Edit monthly picks →</Link></div>{songs.length?<ol className="surface-panel divide-y divide-line">{songs.map((song,index)=><li key={song.id} className="flex items-baseline gap-3 p-4"><span className="text-xs text-muted">{index+1}</span><div className="min-w-0"><p className="text-sm font-semibold text-ink">{song.title}</p><p className="text-xs text-muted">{song.artist}</p></div></li>)}</ol>:<p className="text-sm text-muted">Pick your favourite tracks on an album, or save this month’s favourite songs.</p>}</section>
      <section><h2 className="mb-3 font-serif text-xl font-semibold text-ink">Agree to disagree</h2>{data?.insightsUnavailable?<p role="status" className="text-sm text-accent">Friend comparisons couldn’t load. Your own recap is still available.</p>:recap.disagreements.length?<div className="surface-panel divide-y divide-line">{recap.disagreements.map(row=><Link key={row.album.id+row.person.id} href={`/album/${row.album.id}/compare/${row.person.id}`} className="block p-4"><p className="text-sm font-semibold text-ink">{row.album.title}</p><p className="mt-1 text-sm text-muted">You: {formatScore(row.mine)} · {row.person.name}: {formatScore(row.theirs)} · {formatScore(row.gap)} apart</p></Link>)}</div>:<p className="text-sm text-muted">No visible friend scores differ by 2 or more on this month’s albums.</p>}<p className="mt-2 text-xs text-muted">Compared with accepted friends’ current shared scores, not a historical snapshot.</p></section>
      {recap.albums.length>3&&<section><h2 className="mb-3 font-serif text-xl font-semibold text-ink">All rated or revisited albums</h2><ul className="surface-panel divide-y divide-line">{recap.albums.map(row=><li key={row.album_id}><Link href={`/album/${row.album_id}`} className="flex items-center justify-between gap-3 p-4"><div className="min-w-0"><p className="text-sm text-ink">{row.album!.title}</p><p className="text-xs text-muted">{row.album!.artist}</p></div><ScoreBadge score={Number(row.overall_rating)} className="text-lg"/></Link></li>)}</ul></section>}
      <p className="text-xs leading-relaxed text-muted">Based on the latest saved rating update, grouped in UTC. Editing a score or album notes can move an album between months. Favourite tracks and friend comparisons use current data; these recaps aren’t frozen history.</p>
    </div><RecapShareCard variant="album" data={{month:recapLabel(month),count:recap.albums.length,countLabel:recap.albums.length===1?"album rated or revisited":"albums rated or revisited",detail:recap.average!==null?`${formatScore(recap.average)}/10 average · your saved scores`:"No scored albums updated",highlights:recap.albums.slice(0,3).map(row=>({title:row.album!.title,detail:`${row.album!.artist} · ${formatScore(Number(row.overall_rating))}/10`})),extra:songs.slice(0,2).map(song=>`Favourite: ${song.title} · ${song.artist}`)}}/></div>}
  </div>;
}
